package visitor;

import ast.*;

// This class will be implemented in syntax analysis phase

public class AstPrinter extends DefaultVisitor {

    public static void toHtml(String sourceFile, AST raiz, String filename) {
        // Will be generated by VGen
    }

}
